apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheckconf
data:
  healthcheck.sh: |
    #!/bin/bash
    curl -sq localhost:80
---
apiVersion: nginx.tsuru.io/v1alpha1
kind: Nginx
metadata:
  name: nginx-configmap-hc
spec:
  image: tsuru/nginx-tsuru:1.16.0
  replicas: 1
  healthcheck:
    kind: ConfigMap
    name: healthcheckconf
