name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-contrib/golangci-lint@v1
      with:
        golangci_lint_version: v1.23
        args: run --config ./.golangci.yml ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - run: make test
